### ISSUE TITLE
Better naming of Statistcs Types

### ISSUE THREAD

**Issue by silberjan** [targomo/targomo-js#11]
I propose to make the following changes to the names of the current Types:

| current               | new             |   why       |
|------------------------|------------------|--------------|
|`StatisticsGroup`|`StatisticsList`|The name `StatisticsGroup` is used for the base group on the server side (e.g. 100m x 100m) This type describes a list of statistic value sets |
|`StatisticsSet`|`StatisticsGroupId`|Align it with the server side terminology and add "Id" suffix b/c this only is an id|
|`StatisticsValues`|`RawStatisticValues`| Beause we also rename "Statistics"|
|`Statistics`|`StatisticValues`|"Statistics" is very braod. "StatisticValues" describes the meaning|
|`StatisticsKey`/ `ExtendedStatisticsKey`|`StatisticsItem`|"Key" indicates something id-ish (like in key-value pair). This type holds more info than a key, so we should name it Item|

the changes are reflected and up for discussion in #10

**Comment by abenrob** [comment]
Is anything here proposing changes to the statistics api naming, or is this relating only to the js lib?

**Comment by silberjan** [comment]
this is to align the meaning of the client side classes with the server side terminologies. no changes on the api side have to be made
