### ISSUE TITLE
tgmClient.polygons.fetch firing options request first - causing error

### ISSUE THREAD

**Issue by goors** [targomo/targomo-js#24]
When fire options request i am getting 405 not found or something.

**Comment by hmmmmniek** [comment]
Hey @goors ,
Can you please open your developer tools, go to the network tab and share the request url, request payload and request response with me?
Thanks

**Comment by goors** [comment]
@hmmmmniek I am sorry for opening this ticket. Url was the issue. I was searching instead of region westcetraleurope Switzerland. My bad.
