### ISSUE TITLE
Not receiving lat/lng Geocodes.

### ISSUE THREAD

**Issue by dansnowley-gc** [targomo/targomo-js#41]
I don't seem to be able to receive the Lat/Lng coords for GoogleMaps from the data object being returned. Instead it seems to be returning coords for WGS84/EPSG. 

Maybe I'm completely overlooking something but from the documentation it looks like I should be seeing the geocodes?

Please see attached.

Thanks

![screen shot 2019-02-14 at 08 05 41](https://user-images.githubusercontent.com/25006314/52772083-8c7b5580-302f-11e9-9ba1-f4ff6fbfee82.png)

**Comment by hmmmmniek** [comment]
Hi @dansnowley-gc ,

This is our new reference documentation for PolygonsClient: https://app.targomo.com/tsdocs/core/0.2.8/Polygons/PolygonsClient

Based on the returned data, it seems like you are using PolygonSvgOptions. Which is meant to be used together with our Google Maps/Leaflet extensions library. 
For Google Maps, the class you're looking for is: TgmGoogleMapsPolygonOverlay:
https://app.targomo.com/tsdocs/googlemaps/0.0.4/Other/TgmGoogleMapsPolygonOverlay

If you instead want to get actual Lat/Lng coordinates, you can set the option "serializer" to "geojson".
This will let our service know that you want to receive geojson, which is made up of the Lat/Lng coordinates.

For example:
```
        const client = new tgm.TargomoClient('westcentraleurope', '__targomo_key_here__');

        const sources = [{id: 1, lat: 52.52, lng:  13.405 }];

        const options = {
            travelType: 'walk',
            travelEdgeWeights: [600, 1200],
            srid: 4326,
            serializer: 'geojson'
        };
        client.polygons.fetch(sources, options).then((result) => {
          
        });
```

Let me know if you have any other problems.

**Comment by dansnowley-gc** [comment]
@hmmmmniek Thanks very much for your response.

I should have mentioned that in the screenshot I'm getting that result via the Axios library. I was hoping to be able to bypass using the Targomo library as I already have a method of returning a polygon, so all I really need is the correct Lat/Lng.

Is there no way of getting this without using the Polygon overlay class?

Here is my current connection. Note that adding the 'serializer' parameter just returns a decimal place in the 'WGS84/EPSG' field.

`        const cfgObj = {
            sources: [{
                id: "1",
                lat: "52.52",
                lng: "13.405",
            }],
            edgeWeight: "time",
            polygon: {
                values: [
                    100,
                    200,
                    300
                ],  
            }          
        };

		axios.get(API_ROOT, {
            cancelToken: source.token,
            timeout: 50000,    
            params: {
                key: 'QI80D1Z70C0MEW9D4DYI138897418',
                cfg: cfgObj
            } 
		})
		.then( response => {
			// Check returned data
			if( response ) {
                            resolve(response);
			} else {
				reject('no posts');
			}
		})
		.catch( error => {
			// Reject all but cancelled (as just discarded)
			if (! axios.isCancel(error)) {
				reject(error);
		  }
		});`

Thanks

**Comment by dansnowley-gc** [comment]
I seem to have gotten to the bottom of it. It seems that I was parsing the 'serializer' parameter, but crucially I needed to parse the 'srid' with that.

This wasn't clear from the original documentation that I was looking at [here](https://docs.targomo.com/core/#/Polygon_Service/post_westcentraleurope_v1_polygon).

@hmmmmniek thank you for drawing my attention to this.
