### ISSUE TITLE
Not returning full list of co ordinates for transit. 

### ISSUE THREAD

**Issue by dansnowing** [targomo/targomo-js#42]
I'm currently using Axios to get to the API through a GET request (not using the Targomo library). 

This is working absolutely fine when my travel mode is 'walk', 'cycle' or 'car'. However, when I apply an object for transit I'm seeing what looks like an incomplete list here.  With only 9 results in the array compared to of around 1500+ for walk. 

I have tested the [https://app.route360.net/demo/#!/map?areaID=britishisles&travelTime=30&travelTimeRangeID=0&travelDistanceRangeID=0&travelType=transit&travelDistance=5000&edgeWeight=time&colorRangeID=0&intersection=union&transition=true&zoomAllTheTime=true&mapstyle=light&frameDuration=18000&rushHour=true&sources=51.453493,-2.597394](url) with what I'm trying to retrieve and implemented into my own code. 

The only difference from the demo is that I'm using geojson. When setting to json without an srid code, I get a long list of arrays, with some coordinates that I'm not sure how I can use within my Google map.

Example of the "polygon" coming through on my map.
![image](https://user-images.githubusercontent.com/25006314/53086694-81c43300-34fd-11e9-99a3-d0653fa38609.png)

Any help here would be greatly appreciated.

**Comment by hmmmmniek** [comment]
hey @dansnowing 
Can you send the request URL for this get request that is not working correctly for you?
Concerning your question about the "json" setting, you can easily use those returned results using our targomo-js-extensions library. (https://github.com/targomo/targomo-js-extensions/blob/master/src/google/polygonOverlay.ts)
Which you could use like this:
```
            const map = new google.maps.Map ....
            const options =  {
                ... your options
                serializer: 'json'
            };
            const sources = [{ id: 0, lat: myLatlng.lat(), lng: myLatlng.lng() }];

            const layer = new tgm.googlemaps.TgmGoogleMapsPolygonOverlay(map, {
                strokeWidth: 20
            });

            const polygons = await client.polygons.fetch(sources, options); .. Or fetch with Axios in your case
            layer.setData(polygons);
```

**Comment by dansnowing** [comment]
Hi @hmmmmniek  

Certainly:

`https://api.targomo.com/britishisles/v1/polygon?key=QI80D1Z70C0MEW9D4DYI138897418&cfg=%7B%22sources%22:[%7B%22id%22:%221%22,%22lat%22:%2251.45451%22,%22lng%22:%22-2.58791%22,%22tm%22:%7B%22transit%22:%7B%7D%7D%7D],%22elevation%22:true,%22edgeWeight%22:%22time%22,%22polygon%22:%7B%22values%22:[600],%22intersectionMode%22:%22union%22,%22srid%22:4326,%22serializer%22:%22geojson%22,%22pointReduction%22:true,%22minPolygonHoleSize%22:40000000%7D%7D`

As I'm able to accomplish everything else without the library, and given the size of the current project I'd much prefer not to add another library if possible. 

My hope is that I'm just overlooking a required parameter.

Thanks

**Comment by hmmmmniek** [comment]
I understand you dont always want to introduce new libraries.
I tested your request url, and i seem to get different results compared to you.
Entering the returned geojson in geojson.io, i get something that looks like this:
![image](https://user-images.githubusercontent.com/17322217/53089447-e6d35500-350c-11e9-9840-d1363a15656a.png)

Which seems to be in line with the settings you are using (10 minutes transit)

**Comment by dansnowing** [comment]
Ok, it looks like when it requests from transit the polygons begin to spread from the second array. 

I'm sure that I looked across these multiple times and at no point was receiving the number of coordinates that I am now. 

Perhaps I didn't test my most recent query thoroughly that I ended up sending to you. 

Nonetheless thanks very much for your time. 😄
