### ISSUE TITLE
Deprecate basemaps

### ISSUE THREAD

**Issue by hfs** [targomo/targomo-js#61]
Targomo has decided to discontinue the basemaps at maps.targomo.com.

I don’t know if it would make sense to have support code for one (or several?) of the other map providers? Otherwise just remove the basemaps stuff and leave it to the users to add a basemap of their choice.

Maybe we should start with a deprecation warning before removing it altogether?

CC @abenrob

**Comment by abenrob** [comment]
On hold as we decide on future support
