### ISSUE TITLE
How to use correct region for arbitrary gps coordinates?

### ISSUE THREAD

**Issue by alexfmpe** [targomo/targomo-js#93]
When fetching isochrones (Basic Google Maps Isochrones) from the API, if the provided latlng doesn't match the specified region, the marker shows up correctly, but the isochrone seems to be forced to exist inside the region. It looks like the marker accepts arbitrary latlngs but the source is 'clamped' to inside the region, and that resulting point is used for the isochrone.

Is there a way to not specify the region, or alternatively, compute the matching region for arbitrary gps coordinates?  
Possibly related, can the same api key be used for multiple regions?

**Comment by abenrob** [comment]
Key are valid for all regions. I'm not sure I follow the other part though - you need to identify the specific endpoint, i.e. `westcentraleurope` or `britishisles` ?

**Comment by alexfmpe** [comment]
> you need to identify the specific endpoint, i.e. westcentraleurope or britishisles ?

I'm not using targomo anymore, but the problem was figuring out which endpoint to hit for arbitrary gps coordinates (e.g. coming from some map UI). Hitting the wrong endpoint yielded an incorrectly placed isochrone.

**Comment by abenrob** [comment]
Thanks for the info - there are vague plans to roll out small service to perform that query, but nothing on a timeline. What I have done from time to time is to just use the GeoJSON of the endpoint regions and do the intersection myself... https://www.targomo.com/developers/api/endpoint/. Mentioning for posterity's sake, as you're not currently in need.

**Comment by abenrob** [comment]
> Thanks for the info - there are vague plans to roll out small service to perform that query, but nothing on a timeline. What I have done from time to time is to just use the GeoJSON of the endpoint regions and do the intersection myself... https://www.targomo.com/developers/api/endpoint/. Mentioning for posterity's sake, as you're not currently in need.

We now have a service which can return the endpoint for a given lat,lng

```sh
~ curl https://api.targomo.com/utility/endpoint/\?latitude\=45\&longitude\=-122
{"endpoint":"northamerica"}
```

**Comment by alexfmpe** [comment]
I guess that works, but why not have a single isochrone endpoint take the lat/lng it inevitably requires and internally route to the correct endpoint?
Sounds simpler for application developers and lower latency than asking one endpoint what to tell the other one.

**Comment by abenrob** [comment]
We have dozens of endpoints - isochrone is only a single example. Additionally, we have many, many endpoints, some which are custom, client only, and other which are internal use only, in addition to our main public endpoints - keeping endpoint decoupled is intentional, at least for now.

**Comment by alexfmpe** [comment]
> keeping endpoint decoupled is intentional, at least for now.

Well sure, but if consumers of `/isochrone` need to also consume `/endpoint`, then client code will inevitably couple them. What I was suggesting is that this could be done behind the scenes by the API gateway or so.
